version: 2

updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 30
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 30
    directory: "*"
    schedule:
      interval: "daily"
